# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b51b05a66f2613e32a15a85d45770ad8d8ec25d0678ff3cb37a697e5be6e8b2bf3d717d86e08c3324533baebde78bf2fd1ad7bf948db4903caffea719fcd045

test:
  secret_key_base: e07e8e6681b32a49342c7222f3d81d715da9e248ee1c613bbde6dd4a67ef8a8034fb9424b7f2c2e50b4e59f22787ce3ae1499559e19a3dd49b345f6f4b934b91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
